# Site Settings
locale                   : "en-US"
title                    : "Mahmoud Jalali Mehrabad"
title_separator         : "|"
subtitle                : "Research Scientist | MIT"
name                    : "Mahmoud Jalali Mehrabad"
description             : "Research Scientist at MIT working on quantum photonics, topological photonic circuits, and quantum technologies"
url                     : "https://mahmoudjalalimehrabad.com"
baseurl                 : ""
repository              : "mjalalim3/website"

# Theme
remote_theme            : "academicpages/academicpages.github.io"
minimal_mistakes_skin    : "default"

# Custom styling
minimal_mistakes:
  skin: "default"
  palette:
    primary: "#0066cc"
    secondary: "#004499"

# Include files/folders  
include:
  - _pages

# SEO
twitter:
  username              : "mjalalimehrabad"
  card                  : "summary_large_image"

# Social
social:
  name                  : "Mahmoud Jalali Mehrabad"
  links:
    - "mailto:mjalalim3@gmail.com"
    - "https://scholar.google.com/citations?user=CqtiZuEAAAAJ"
    - "https://orcid.org/0000-0002-9809-9998"
    - "https://github.com/mjalalim3"
    - "https://www.linkedin.com/in/mahmoud-jalali-mehrabad-7a46a5100"
    - "https://x.com/mjalalimehrabad"
    - "https://arxiv.org/search/?query=Mahmoud+Jalali+Mehrabad&searchtype=author"
    - "https://qp.mit.edu/team"

# Author information
author:
  name                  : "Mahmoud Jalali Mehrabad"
  avatar                : "profile.jpg"
  bio                   : "Research Scientist | MIT"
  location              : "Cambridge, MA"
  email                 : "mjalalim3@gmail.com"
  uri                   : "https://scholar.google.com/citations?user=CqtiZuEAAAAJ"
  orcid                 : "0000-0002-9809-9998"
  google_scholar        : "CqtiZuEAAAAJ"
  github                : "mjalalim3"
  linkedin              : "mahmoud-jalali-mehrabad-7a46a5100"
  twitter               : "mjalalimehrabad"
  arxiv                 : "Mahmoud+Jalali+Mehrabad"
  research_group        : "https://qp.mit.edu/team"

# Build Settings
markdown                 : kramdown
highlighter             : rouge
permalink               : /:categories/:title/
timezone                 : "America/New_York"

# Collections
collections:
  publications:
    output              : true
    permalink           : /:collection/:name/
  talks:
    output              : true
    permalink           : /:collection/:name/
  teaching:
    output              : true
    permalink           : /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-include-cache