# Site Settings
locale                   : "en-US"
title                    : "Mahmoud Jalali Mehrabad"
title_separator         : "|"
subtitle                : "Research Scientist | MIT"
name                    : "Mahmoud Jalali Mehrabad"
description             : "Research Scientist at MIT working on quantum photonics, topological photonic circuits, and quantum technologies"
url                     : "https://mahmoudjalalimehrabad.com"
baseurl                 : ""
repository              : "mjalalim3/website"

# Theme
remote_theme            : "academicpages/academicpages.github.io"

# Include files/folders  
include:
  - _pages

# SEO
twitter:
  username              : "mjalalimehrabad"
  card                  : "summary_large_image"

# Social
social:
  name                  : "Mahmoud Jalali Mehrabad"
  links:
    - "https://github.com/mjalalim3"
    - "https://scholar.google.com/citations?user=CqtiZuEAAAAJ"
    - "https://www.linkedin.com/in/mahmoud-jalali-mehrabad-7a46a5100"
    - "https://x.com/mjalalimehrabad"
    - "mailto:mjalalim3@gmail.com"

# Author information
author:
  name                  : "Mahmoud Jalali Mehrabad"
  avatar                : "images/profile.jpg"
  bio                   : "Research Scientist at MIT"
  location              : "Cambridge, MA"
  email                 : "mjalalim3@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mjalalim3@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=CqtiZuEAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mjalalim3"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mahmoud-jalali-mehrabad-7a46a5100"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/mjalalimehrabad"
    - label: "arXiv"
      icon: "ai ai-arxiv"
      url: "https://arxiv.org/search/?query=Mahmoud+Jalali+Mehrabad&searchtype=author"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-9809-9998"
    - label: "Research Group"
      icon: "fas fa-fw fa-users"
      url: "https://qp.mit.edu/team"

# Build Settings
markdown                 : kramdown
highlighter             : rouge
permalink               : /:categories/:title/
timezone                 : "America/New_York"

# Collections
collections:
  publications:
    output              : true
    permalink           : /:collection/:name/
  talks:
    output              : true
    permalink           : /:collection/:name/
  teaching:
    output              : true
    permalink           : /:collection/:name/
  portfolio:
    output              : true
    permalink           : /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag